# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site.
# For technical reasons, this file is *NOT* reloaded automatically. 
# If you change this file, please restart the server or push to GitHub.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Site Title"
title_separator          : "-"
name                     : &name "Izzat Ahmad Adly"
description              : &description "Ph.D. Candidate in Economics"
url                      : "https://izzatadly.github.io" 
baseurl                  : "" 
repository               : "izzatadly/izzatadly.github.io" # Fixed repository path

# Site Author - Controls the sidebar content.
author:
  # Biographic information
  avatar           : "profile.png" # Place your photo in the /images/ folder and name it profile.png
  name             : "Izzat Bin Ahmad Adly"
  pronouns         : 
  bio              : "Ph.D. Candidate in Economics"
  location         : "Lincoln, Nebraska"
  employer         : "University of Nebraska-Lincoln"
  uri              : 
  email            : "iahmadadly2@huskers.unl.edu" 

  # Repositories and software development
  github           : "izzatadly"

  # Academic & Social (Left blank to hide them from the sidebar)
  googlescholar    : 
  orcid            : 
  pubmed           : 
  twitter          : 
  linkedin         : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled" 
talkmap_link             : false      

# Analytics (Set to false to prevent tracking errors)
analytics:
  provider               : "false" 

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .github
  - node_modules
  - package.json
  - README
  - vendor

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

# Collections (These control your research/teaching pages)
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
